# Custom builder. The python script will
#   - request duffy instances
#   - ssh to them, git clone $GIT_REPO_URL
#   - execute $TEST_CMD on them
- builder:
    name: centos-ci-bootstrap
    builders:
        - python:
            !include-raw:
                - ./run.py

# Custom Trigger. Sets up the Github pull request trigger
# Accepts a parameter {provider}
- trigger:
    name: custom-trigger
    triggers:
        - github-pull-request:
            admin-list:
              - dustymabe
              - cdrage
              - rtnpro
              - kadel
            white-list:
              - dustymabe
              - cdrage
              - rtnpro
              - kadel
            build-desc-template: "build description"
            trigger-phrase: '#dotests|#dotest{provider}'
            only-trigger-phrase: {only-trigger-phrase}
            github-hooks: true
            permit-all: false
            auto-close-on-fail: false
            status-context: "{provider} tests"
            started-status: "centos-ci {provider} test started"
            success-status: "centos-ci {provider} test succeeded"
            failure-status: "centos-ci {provider} test failed"
            error-status: "centos-ci {provider} test errored"
            build-desc-template: ''

# Custom Publisher for sending email
- publisher:
    name: custom-publisher-email
    publishers:
        - email:
            recipients: 'container-tools@redhat.com'

# Custom Publisher for irc notifications
- publisher:
    name: custom-publisher-irc
    publishers:
        - ircbot:
            strategy: all
            channels:
                - name: '#nulecule'
# Custom SCM section for our git repo
- scm:
    name: custom-scm-git
    scm: 
      - git:
          url: https://github.com/projectatomic/atomicapp.git
          git-tool: ci-git
          wipe-workspace: false
          skip-tag: true
          clean:
            after: true
          credentials-id: 1d7dba44-5b34-42b3-886c-4d659ffb2aae
          refspec: "{refspec}"
          branches:
              - "{branch}"

# job template for each provider to test against master
- job-template:
    name: '{name}-{provider}-master'
    # restrict to nodes that are set up for atomicapp
    node: atomicapp-shared
    properties:
        - github:
            url: "{git_repo_url}"
    scm:
        - custom-scm-git:
            refspec: "{refspec}"
            branch: "master"
    publishers:
        - custom-publisher-email
        - custom-publisher-irc
    builders:
        - inject:
            properties-content: |
                GIT_REPO_URL="{git_repo_url}"
                MACHINE_COUNT=1
                TEST_CMD='{test_cmd_master}'
        - centos-ci-bootstrap

# job template for each provider to test PRs using GHPRB
- job-template:
    name: '{name}-{provider}-pr'
    # restrict to nodes set up for atomicapp
    node: atomicapp-shared
    properties:
        - github:
            url: "{git_repo_url}"
    scm:
        - custom-scm-git:
            refspec: "{refspec}"
            branch: "{branch}"
    triggers:
        - custom-trigger:
            provider: "{provider}"
            only-trigger-phrase: {only-trigger-false}

    publishers:
        - custom-publisher-email
        - custom-publisher-irc
    builders:
        - inject:
            properties-content: |
                PROVIDER={provider}
                GIT_REPO_URL="{git_repo_url}"
                MACHINE_COUNT=1
                TEST_CMD = '{test_cmd}'
        - centos-ci-bootstrap

# create the jobs using the job templates
- project:
    name: atomicapp-test
    provider:
        - docker
        - kubernetes
        - openshift
        - unittest:
            git_repo_url: "https://github.com/projectatomic/atomicapp"
            refspec: "+refs/pull/*:refs/remotes/origin/pr/*"
            branch: "${{sha1}}"
            test_cmd_master: 'make test'
            test_cmd: 'make test'
    refspec: ""
    branch: ""
    only-trigger-phrase: true
    git_repo_url: https://github.com/projectatomic/adb-tests.git
    test_cmd: 'cd cdrage-atomicapp-ci/ && make install {provider} ATOMICAPP_PR=$ghprbPullId ATOMIC_SOURCE=rpm'
    test_cmd_master: 'cd cdrage-atomicapp-ci/ && make install {provider} ATOMIC_SOURCE=rpm'
    jobs:
      - '{name}-{provider}-pr'
      - '{name}-{provider}-master'
